# Generated by Django 5.2.4 on 2025-07-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0003_monthlyincome'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyincome',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='monthlyincome',
            name='month',
            field=models.DateField(),
        ),
    ]
